# Generated by Django 3.1.4 on 2023-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etxea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_izena', models.CharField(max_length=100)),
                ('e_herria', models.CharField(max_length=100)),
                ('e_pertsonakopurua', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nan', models.CharField(max_length=100)),
                ('p_izena', models.CharField(max_length=100)),
                ('p_emaila', models.CharField(max_length=100)),
            ],
        ),
    ]
